"""init

Revision ID: e903a6feb0bd
Revises: 
Create Date: 2025-04-11 21:35:54.865846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e903a6feb0bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=100), nullable=True),
    sa.Column('sender_first_name', sa.String(length=100), nullable=True),
    sa.Column('sender_last_name', sa.String(length=100), nullable=True),
    sa.Column('sender_username', sa.String(length=100), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('topic_name', sa.String(length=255), nullable=True),
    sa.Column('update_data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_messages_chat_id'), 'telegram_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_telegram_messages_id'), 'telegram_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_messages_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_messages_chat_id'), table_name='telegram_messages')
    op.drop_table('telegram_messages')
    # ### end Alembic commands ###
